apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: travel-memory   # fixed namespace name
type: Opaque
data:
  # Base64 encoded values
  MONGO_URI: <BASE64_ENCODED_MONGO_URI>
  PORT: <BASE64_ENCODED_PORT>
