apiVersion: v1
kind: Secret
metadata:
  name: travel-memory-secret
  namespace: travel-memory
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"          # put real username
  MONGO_INITDB_ROOT_PASSWORD: "s3cr3tPass"     # real password
