#[web]
#localhost ansible_connection=local

#[db]
#10.0.2.45

#[all:vars]
#ansible_user=ubuntu
#ansible_ssh_private_key_file=./MERNAppAdishKeyPair.pem
#ansible_python_interpreter=/usr/bin/python3


[web]
10.0.1.246 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/MERNAppAdishKeyPair.pem

[db]
10.0.2.154 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/MERNAppAdishKeyPair.pem
