- name: Harden EC2 Security
  hosts: all
  become: yes

  vars:
    ssh_port: 22
    app_port: 3000
    mongo_port: 27017

  tasks:

    - name: Disable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'

    - name: Restart SSH
      service:
        name: ssh
        state: restarted

    - name: Install UFW firewall
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Allow SSH
      ufw:
        rule: allow
        port: "{{ ssh_port }}"
        proto: tcp

    - name: Allow Application Port
      ufw:
        rule: allow
        port: "{{ app_port }}"
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny
