- name: Setup Web Server
  hosts: web
  become: yes

  tasks:

    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Node.js
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt install -y nodejs
      args:
        executable: /bin/bash

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes

    - name: Install Git
      apt:
        name: git
        state: present
